### ISSUE TITLE
Unable to run serverside

### ISSUE THREAD

**Issue by ASVincent** [planetlabs/planet-client-js#65]
Not sure if this is outside the scope of this client implementation but I wanted to run the client both server-side (within a node context) and client-side (browser-context).

The reason is to be able to target multiple use-cases and reuse a planet-api utility library to abstract common tasks under different assumptions.

When using search api '@planet/client/api/search' the first issue I run into is the use of XMLHttpRequest, after installing an xmlhttprequest module and adding a polyfill into the global namespace I run into a secondary problem.

```
TypeError: Cannot read property 'target' of undefined
```
This is at `node_modules/@planet/client/api/request.js:122;, no target is defined for a load event that the API is listening for (the target is expected to be the client).

Is there any enthusiasm for enabling the client to be run within a node context?

@planet/client: 3.1.0
xmlhttprequest2: 1.0.1

N.B. I stopped exploring after hitting these issues and decided to ask here; there may be other problems generalising this client to run server-side.

**Comment by tschaub** [comment]
Thanks for opening the issue @ASVincent.  I'm guessing you'll have better luck with the [`xhr2`](https://www.npmjs.com/package/xhr2) package.  In #66, I've updated the tests to run in Node.  A subset of these tests uses the `xhr2` package to provide `XMLHttpRequest`.
